// tests/fixtures/make.mjs — synthetic messy-tree generator.
// [TESTED: 2026-07-24 · npm test 5/5 green (tests/fixtures.test.mjs) + CLI smoke run into scratchpad]
//
// Builds a deterministic "chaotic archive" fixture tree with KNOWN-CORRECT answers, so every later
// KPOT phase (scan/meta/dedupe/plan/apply) can be verified objectively without a human and without
// ever touching a real archive. The case catalog mirrors the real-chaos survey in
// researches/02_real_archive_survey.md: date-in-filename patterns, epoch-named files, camera-serial
// names needing EXIF, social-export names with no evidence, "+"-twins, Cyrillic names (including a
// Cyrillic *extension*), an already-hand-sorted year/season subtree, junk files, non-media files,
// audio, video with an mvhd date, a broken-camera-clock date, and byte-identical duplicates.
//
// Every generated byte is fixed (no randomness, no clock reads) — two runs produce identical trees.
// Alongside the tree it writes `expected.json`: the ground-truth manifest tests assert against.
//
// Usage:  node tests/fixtures/make.mjs <targetDir>          (CLI)
//         const m = await makeFixtureTree(dir)              (from tests)

import { mkdir, writeFile, utimes } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import process from 'node:process';
import jpegJs from 'jpeg-js';

/** Version stamp of the fixture catalog — bump when cases change so stale trees are detectable. */
export const FIXTURE_VERSION = 6; // v6 (2026-07-28): +2 cases — a reset camera clock (1 Jan 00:25 in
                                  // a collection that starts in 2008) and its counter-case, a REAL
                                  // New Year photo at 00:40 that must survive the same rule
                                  // v5 (2026-07-28): +6 cases — plans/02 §Шаг 2: JPEGs with REAL
                                  // decodable pixels, an editor crop whose original is in the tree
                                  // (found by pixels) and one whose original is absent (must stay
                                  // honestly undated)
                                  // v4 (2026-07-28): +6 cases — sidecars (researches/04): a THM
                                  // beside its AVI twin, an orphan THM, an XMP that dates its
                                  // photo, and an XMP that carries only a save date (dates nothing)
                                  // v3 (2026-07-27): +7 cases — the plans/02 editor-export classes
                                  // (family geometry, XMP DerivedFrom original, honest ПРОЧЕЕ)

/** Seconds between the QuickTime epoch (1904-01-01) and the Unix epoch (1970-01-01). */
const QT_EPOCH_OFFSET = 2082844800;

/** A fixed "bulk copy day" mtime planted on files whose filesystem time must NOT be trusted. */
const COPY_SPIKE_MTIME = new Date('2023-05-15T12:00:00Z');

/** The mtime every other planted file gets, so the tree never depends on the generation-time clock. */
const FIXED_MTIME = new Date('2015-01-01T00:00:00Z');

// ---------------------------------------------------------------------------
// Binary builders — minimal but magic-correct file bodies.
// They are as small as honesty allows: metadata segments are real and parseable; pixel/sound data
// is NOT decodable (KPOT never decodes pixels — see researches/01_prior_art.md §1).
// ---------------------------------------------------------------------------

/**
 * Minimal JPEG: SOI + optional APP1/Exif (with a real TIFF IFD carrying DateTimeOriginal) +
 * a COM segment holding `uniq` (differentiates file bytes) + EOI.
 * @param {string|null} exifDate  "YYYY:MM:DD HH:MM:SS" or null for no EXIF
 * @param {string} uniq           unique padding so distinct files are not accidental byte-duplicates
 */
export function makeJpeg(exifDate, uniq) {
  const parts = [Buffer.from([0xFF, 0xD8])]; // SOI
  if (exifDate) {
    // TIFF (little-endian): IFD0 with one entry → ExifIFD; ExifIFD with one entry → DateTimeOriginal.
    const tiff = Buffer.alloc(64);
    tiff.write('II', 0, 'ascii'); tiff.writeUInt16LE(42, 2); tiff.writeUInt32LE(8, 4);
    tiff.writeUInt16LE(1, 8);                              // IFD0: 1 entry
    tiff.writeUInt16LE(0x8769, 10); tiff.writeUInt16LE(4, 12); // ExifIFD pointer, LONG
    tiff.writeUInt32LE(1, 14); tiff.writeUInt32LE(26, 18);
    tiff.writeUInt32LE(0, 22);                             // next IFD: none
    tiff.writeUInt16LE(1, 26);                             // ExifIFD: 1 entry
    tiff.writeUInt16LE(0x9003, 28); tiff.writeUInt16LE(2, 30); // DateTimeOriginal, ASCII
    tiff.writeUInt32LE(20, 32); tiff.writeUInt32LE(44, 36);
    tiff.writeUInt32LE(0, 40);                             // next IFD: none
    tiff.write(exifDate + '\0', 44, 'ascii');              // 20 bytes incl. NUL
    const payload = Buffer.concat([Buffer.from('Exif\0\0', 'ascii'), tiff]);
    const app1 = Buffer.alloc(4);
    app1.writeUInt16BE(0xFFE1, 0); app1.writeUInt16BE(payload.length + 2, 2);
    parts.push(app1, payload);
  }
  const comText = Buffer.from('kpot-fixture:' + uniq, 'ascii'); // COM segment = per-file uniqueness
  const com = Buffer.alloc(4);
  com.writeUInt16BE(0xFFFE, 0); com.writeUInt16BE(comText.length + 2, 2);
  parts.push(com, comText, Buffer.from([0xFF, 0xD9])); // EOI
  return Buffer.concat(parts);
}

/**
 * Minimal MP4: `ftyp` + `moov/mvhd` with a real creation_time (QuickTime epoch, UTC).
 * @param {string|null} isoUtc  e.g. "2016-12-10T10:09:50Z", or null for creation_time = 0 (unset)
 */
export function makeMp4(isoUtc, uniq) {
  const ftyp = Buffer.alloc(16);
  ftyp.writeUInt32BE(16, 0); ftyp.write('ftyp', 4, 'ascii');
  ftyp.write('isom', 8, 'ascii'); ftyp.writeUInt32BE(0, 12);
  const mvhd = Buffer.alloc(108);
  mvhd.writeUInt32BE(108, 0); mvhd.write('mvhd', 4, 'ascii'); // version 0, flags 0
  const secs = isoUtc ? Math.floor(Date.parse(isoUtc) / 1000) + QT_EPOCH_OFFSET : 0;
  mvhd.writeUInt32BE(secs, 12);        // creation_time
  mvhd.writeUInt32BE(secs, 16);        // modification_time
  mvhd.writeUInt32BE(1000, 20);        // timescale
  mvhd.writeUInt32BE(0, 24);           // duration
  mvhd.writeUInt32BE(0x00010000, 28);  // rate 1.0
  mvhd.writeUInt16BE(0x0100, 32);      // volume 1.0
  const moov = Buffer.alloc(8);
  moov.writeUInt32BE(8 + 108, 0); moov.write('moov', 4, 'ascii');
  // `free` box carries per-file uniqueness (real MP4s allow it anywhere top-level)
  const uniqBytes = Buffer.from('kpot-fixture:' + uniq, 'ascii');
  const free = Buffer.alloc(8);
  free.writeUInt32BE(8 + uniqBytes.length, 0); free.write('free', 4, 'ascii');
  return Buffer.concat([ftyp, moov, mvhd, free, uniqBytes]);
}

/**
 * Full-featured JPEG for the plans/02 editor-export cases: a real little-endian TIFF with a
 * multi-entry IFD0 (Make/Model/Software/DateTime) and an optional ExifIFD (DateTimeOriginal),
 * an optional XMP APP1 packet (DocumentID / DerivedFrom — the Photoshop identity chain), and an
 * optional SOF0 carrying real pixel dimensions (what family geometry reads). Every offset is
 * computed, every segment parseable — "the date is really in the file" stays assertable.
 *
 * With `pixels` it becomes a REAL image: the RGBA buffer is encoded by jpeg-js and our metadata
 * segments are spliced in after the encoder's JFIF header, so the file carries genuine decodable
 * pixel data AND a genuine EXIF/XMP block. `width`/`height` are then taken from the pixels
 * themselves — the fake SOF0 is not written, because a real one already exists.
 *
 * @param {{dateTimeOriginal?: string|null, dateTime?: string|null, software?: string|null,
 *          make?: string|null, model?: string|null, width?: number|null, height?: number|null,
 *          documentId?: string|null, derivedFromDocumentId?: string|null,
 *          pixels?: {data: Uint8Array, width: number, height: number}|null,
 *          quality?: number, uniq: string}} opts
 */
export function makeJpegEx({ dateTimeOriginal = null, dateTime = null, software = null,
                             make = null, model = null, width = null, height = null,
                             documentId = null, derivedFromDocumentId = null,
                             pixels = null, quality = 85, uniq }) {
  const parts = [Buffer.from([0xFF, 0xD8])]; // SOI

  // --- APP1/Exif: IFD0 entries in ascending tag order (TIFF requirement) ---
  const ifd0 = [];
  if (make) ifd0.push({ tag: 0x010F, value: make });
  if (model) ifd0.push({ tag: 0x0110, value: model });
  if (software) ifd0.push({ tag: 0x0131, value: software });
  if (dateTime) ifd0.push({ tag: 0x0132, value: dateTime });
  const hasExifIfd = Boolean(dateTimeOriginal);
  if (ifd0.length > 0 || hasExifIfd) {
    const n0 = ifd0.length + (hasExifIfd ? 1 : 0);       // +1 for the ExifIFD pointer entry
    const ifd0Start = 8;
    const exifIfdStart = ifd0Start + 2 + n0 * 12 + 4;
    const exifIfdSize = hasExifIfd ? 2 + 1 * 12 + 4 : 0;
    const dataStart = exifIfdStart + exifIfdSize;
    const asciiBytes = (v) => v.length + 1; // incl. NUL
    const dataTotal = ifd0.reduce((s, e) => s + (asciiBytes(e.value) > 4 ? asciiBytes(e.value) : 0), 0)
      + (hasExifIfd ? asciiBytes(dateTimeOriginal) : 0);
    const tiff = Buffer.alloc(dataStart + dataTotal);
    tiff.write('II', 0, 'ascii'); tiff.writeUInt16LE(42, 2); tiff.writeUInt32LE(ifd0Start, 4);
    let dataOff = dataStart;
    const writeAscii = (at, tag, value) => {
      const bytes = asciiBytes(value);
      tiff.writeUInt16LE(tag, at); tiff.writeUInt16LE(2, at + 2); // type ASCII
      tiff.writeUInt32LE(bytes, at + 4);
      if (bytes <= 4) { tiff.write(value + '\0', at + 8, 'ascii'); }
      else { tiff.writeUInt32LE(dataOff, at + 8); tiff.write(value + '\0', dataOff, 'ascii'); dataOff += bytes; }
    };
    tiff.writeUInt16LE(n0, ifd0Start);
    ifd0.forEach((e, i) => writeAscii(ifd0Start + 2 + i * 12, e.tag, e.value));
    if (hasExifIfd) {
      const at = ifd0Start + 2 + ifd0.length * 12;       // the last IFD0 entry: the ExifIFD pointer
      tiff.writeUInt16LE(0x8769, at); tiff.writeUInt16LE(4, at + 2); // type LONG
      tiff.writeUInt32LE(1, at + 4); tiff.writeUInt32LE(exifIfdStart, at + 8);
    }
    tiff.writeUInt32LE(0, ifd0Start + 2 + n0 * 12);      // IFD0: next IFD = none
    if (hasExifIfd) {
      tiff.writeUInt16LE(1, exifIfdStart);               // ExifIFD: 1 entry
      writeAscii(exifIfdStart + 2, 0x9003, dateTimeOriginal); // DateTimeOriginal
      tiff.writeUInt32LE(0, exifIfdStart + 2 + 12);      // next IFD: none
    }
    const payload = Buffer.concat([Buffer.from('Exif\0\0', 'ascii'), tiff]);
    const app1 = Buffer.alloc(4);
    app1.writeUInt16BE(0xFFE1, 0); app1.writeUInt16BE(payload.length + 2, 2);
    parts.push(app1, payload);
  }

  // --- APP1/XMP: the identity chain Photoshop-class editors write ---
  if (documentId || derivedFromDocumentId) {
    const xml = '<x:xmpmeta xmlns:x="adobe:ns:meta/">'
      + '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
      + '<rdf:Description rdf:about="" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"'
      + ' xmlns:stRef="http://ns.adobe.com/xap/1.0/sType/ResourceRef#"'
      + (documentId ? ` xmpMM:DocumentID="${documentId}"` : '')
      + '>'
      + (derivedFromDocumentId
        ? `<xmpMM:DerivedFrom stRef:documentID="${derivedFromDocumentId}"/>` : '')
      + '</rdf:Description></rdf:RDF></x:xmpmeta>';
    const payload = Buffer.concat([
      Buffer.from('http://ns.adobe.com/xap/1.0/\0', 'ascii'), Buffer.from(xml, 'utf8')]);
    const app1 = Buffer.alloc(4);
    app1.writeUInt16BE(0xFFE1, 0); app1.writeUInt16BE(payload.length + 2, 2);
    parts.push(app1, payload);
  }

  // --- SOF0: real pixel dimensions (family geometry evidence reads these) ---
  if (width && height && !pixels) {
    const sof = Buffer.alloc(19);
    sof.writeUInt16BE(0xFFC0, 0); sof.writeUInt16BE(17, 2);
    sof[4] = 8; sof.writeUInt16BE(height, 5); sof.writeUInt16BE(width, 7); sof[9] = 3;
    sof.set([1, 0x22, 0, 2, 0x11, 1, 3, 0x11, 1], 10);
    parts.push(sof);
  }

  const comText = Buffer.from('kpot-fixture:' + uniq, 'ascii'); // COM segment = per-file uniqueness
  const com = Buffer.alloc(4);
  com.writeUInt16BE(0xFFFE, 0); com.writeUInt16BE(comText.length + 2, 2);
  parts.push(com, comText);

  if (pixels) {
    // A real JPEG: encode the pixels, then insert our metadata segments AFTER the encoder's JFIF
    // APP0 (which every decoder expects first) and before the tables and the scan.
    const encoded = Buffer.from(jpegJs.encode(pixels, quality).data);
    const meta = Buffer.concat(parts.slice(1)); // everything except our own SOI
    const afterApp0 = encoded[2] === 0xFF && encoded[3] === 0xE0 ? 4 + encoded.readUInt16BE(4) : 2;
    return Buffer.concat([encoded.subarray(0, afterApp0), meta, encoded.subarray(afterApp0)]);
  }
  parts.push(Buffer.from([0xFF, 0xD9])); // EOI
  return Buffer.concat(parts);
}

// ---------------------------------------------------------------------------
// Real pixels — for plans/02 §Шаг 2 (finding an export's original BY ITS PIXELS).
// Every other builder above writes metadata-only files on purpose: KPOT decodes nothing to date a
// file. The pixel search is the one feature that must actually look at an image, so its fixture
// cases carry genuinely decodable JPEGs — synthetic, deterministic, and tiny.
// ---------------------------------------------------------------------------

/** xorshift32 — a deterministic generator. `Math.random` must never appear in a fixture: two runs
 *  of this file have to produce byte-identical trees (AGENT_GUIDE §canonical order). */
function xorshift(seed) {
  let s = (seed >>> 0) || 1;
  return () => {
    s ^= s << 13; s >>>= 0;
    s ^= s >> 17;
    s ^= s << 5; s >>>= 0;
    return s / 4294967296;
  };
}

/**
 * A synthetic "photograph": a coarse random luminance landscape (which is what a block-mean hash
 * actually sees) plus a fine deterministic texture (which is what tells two similar frames apart).
 * Both are functions of ABSOLUTE x/y, so a crop of this image is a true sub-window of it — exactly
 * the relationship a real crop has to its original.
 *
 * @param {{width: number, height: number, seed: number}} opts
 * @returns {{data: Uint8Array, width: number, height: number}}  RGBA, as jpeg-js expects
 */
export function photoPixels({ width, height, seed }) {
  const CELLS = 8; // coarse structure: an 8×8 luminance landscape
  const rnd = xorshift(seed);
  const grid = new Float64Array((CELLS + 1) * (CELLS + 1));
  for (let i = 0; i < grid.length; i += 1) grid[i] = rnd() * 255;
  const data = new Uint8Array(width * height * 4);
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const gx = (x / width) * CELLS;
      const gy = (y / height) * CELLS;
      const x0 = Math.floor(gx); const y0 = Math.floor(gy);
      const fx = gx - x0; const fy = gy - y0;
      const at = (cx, cy) => grid[cy * (CELLS + 1) + cx];
      const top = at(x0, y0) * (1 - fx) + at(x0 + 1, y0) * fx;
      const bottom = at(x0, y0 + 1) * (1 - fx) + at(x0 + 1, y0 + 1) * fx;
      const texture = 18 * Math.sin((x * 0.7 + seed * 0.01)) * Math.cos(y * 0.5 + seed * 0.02);
      const v = Math.max(0, Math.min(255, Math.round(top * (1 - fy) + bottom * fy + texture)));
      const i = (y * width + x) * 4;
      data[i] = v; data[i + 1] = v; data[i + 2] = v; data[i + 3] = 255;
    }
  }
  return { data, width, height };
}

/** Crop an RGBA image the way an editor export is cropped: full height, part of the width. */
export function cropPixels({ data, width, height }, { keep = 0.7, offsetFrac = 0.15 } = {}) {
  const w = Math.round(width * keep);
  const x0 = Math.round((width - w) * offsetFrac);
  const out = new Uint8Array(w * height * 4);
  for (let y = 0; y < height; y += 1) {
    const src = (y * width + x0) * 4;
    out.set(data.subarray(src, src + w * 4), y * w * 4);
  }
  return { data: out, width: w, height };
}

/** Minimal PNG: real signature + IHDR/IEND shells (CRCs zeroed — magic-detection fixtures only). */
export function makePng(uniq) {
  const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  const ihdr = Buffer.alloc(25); // len(4) 'IHDR' 13-byte body + zero CRC
  ihdr.writeUInt32BE(13, 0); ihdr.write('IHDR', 4, 'ascii');
  ihdr.writeUInt32BE(1, 8); ihdr.writeUInt32BE(1, 12); ihdr[16] = 8; ihdr[17] = 0;
  const text = Buffer.from('kpot-fixture:' + uniq, 'ascii');
  const iend = Buffer.alloc(12); iend.write('IEND', 4, 'ascii');
  return Buffer.concat([sig, ihdr, text, iend]);
}

/** Minimal OGG: real 'OggS' magic + uniqueness padding. */
export function makeOgg(uniq) {
  return Buffer.concat([Buffer.from('OggS\0\0\0\0', 'ascii'), Buffer.from('kpot-fixture:' + uniq)]);
}

/**
 * Minimal AVI: the RIFF header with the `AVI ` form type — which is all `identify` reads, and all
 * a date extractor CAN read: AVI is RIFF, not ISO-BMFF, so `mp4.mjs` finds no `moov` and yields
 * nothing. That is exactly the real situation researches/04 §4 measured on 25 of the owner's
 * videos, and it is what makes their THM twin the only date they have.
 */
export function makeAvi(uniq) {
  const body = Buffer.from('kpot-fixture:' + uniq, 'ascii');
  const head = Buffer.alloc(12);
  head.write('RIFF', 0, 'ascii');
  head.writeUInt32LE(4 + body.length, 4); // RIFF chunk size: form type + payload
  head.write('AVI ', 8, 'ascii');
  return Buffer.concat([head, body]);
}

/**
 * An XMP sidecar file: a real xpacket-wrapped RDF document, shaped like the one observed in the
 * archive (researches/04 §5 — `XMP Core 5.5.0`, properties as attributes on rdf:Description).
 * `dateTimeOriginal` is a CAPTURE claim; `modifyDate` is a SAVE time that must date nothing.
 */
export function makeXmp({ dateTimeOriginal = null, modifyDate = null }) {
  const props = (dateTimeOriginal ? ` exif:DateTimeOriginal="${dateTimeOriginal}"` : '')
    + (modifyDate ? ` xmp:ModifyDate="${modifyDate}"` : '');
  return Buffer.from(
    '<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>'
    + '<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.5.0">'
    + '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
    + '<rdf:Description rdf:about=""'
    + ' xmlns:exif="http://ns.adobe.com/exif/1.0/"'
    + ' xmlns:xmp="http://ns.adobe.com/xap/1.0/"'
    + props + '/>'
    + '</rdf:RDF></x:xmpmeta><?xpacket end="w"?>', 'utf8');
}

const text = (s) => Buffer.from(s, 'utf8');

// ---------------------------------------------------------------------------
// The case catalog — one entry per planted file.
// expected.date is the GROUND-TRUTH capture date ("YYYY-MM-DD HH:MM:SS" local, or null = undatable);
// expected.evidence names the strongest evidence KPOT is supposed to find it by.
// ---------------------------------------------------------------------------

/** @returns the full planted-case list (path separators are '/', converted on write) */
export function catalog() {
  // plans/02 §Шаг 2 — the pixel cases. One camera dump holding four originals from FOUR DIFFERENT
  // YEARS (so the camera family cannot narrow the year: only the pixels can answer) and two editor
  // crops — one whose original is planted here, one whose original was never planted at all.
  const shots = {
    a: photoPixels({ width: 320, height: 240, seed: 20110504 }),
    b: photoPixels({ width: 320, height: 240, seed: 20120615 }),
    c: photoPixels({ width: 320, height: 240, seed: 20130720 }),
    d: photoPixels({ width: 320, height: 240, seed: 20140805 }),
    lost: photoPixels({ width: 320, height: 240, seed: 19990101 }), // deliberately NEVER planted
  };
  return [
    // — date in the filename (Android camera convention) —
    { path: 'Мобилка/IMG_20140121_183801.jpg', body: makeJpeg(null, 'and1'),
      expected: { kind: 'photo', date: '2014-01-21 18:38:01', evidence: 'filename' } },
    // — "+"-twin pair: one char apart, different bytes, must NOT be merged as duplicates —
    { path: 'Мобилка/IMG_20140121_184626.jpg', body: makeJpeg(null, 'twinA'),
      expected: { kind: 'photo', date: '2014-01-21 18:46:26', evidence: 'filename', twin: 'plus-pair' } },
    { path: 'Мобилка/IMG_20140121_184626+.jpg', body: makeJpeg(null, 'twinB'),
      expected: { kind: 'photo', date: '2014-01-21 18:46:26', evidence: 'filename', twin: 'plus-pair' } },
    // — camera serial names, EXIF is the only evidence; three confident 2011 files make this
    //   device-dump dir a cohort for the EXIF-less neighbor below (owner decision 2026-07-24) —
    { path: '100MEDIA/IMAG0178.jpg', body: makeJpeg('2011:03:04 09:15:00', 'htc2'),
      expected: { kind: 'photo', date: '2011-03-04 09:15:00', evidence: 'exif' } },
    { path: '100MEDIA/IMAG0179.jpg', body: makeJpeg('2011:03:05 11:02:10', 'htc3'),
      expected: { kind: 'photo', date: '2011-03-05 11:02:10', evidence: 'exif' } },
    { path: '100MEDIA/IMAG0180.jpg', body: makeJpeg('2011:03:05 14:20:33', 'htc1'),
      expected: { kind: 'photo', date: '2011-03-05 14:20:33', evidence: 'exif' } },
    // — EXIF-less file among confidently-dated neighbors → ASSUMED year via dir cohort, must be
    //   marked assumed and surfaced to the owner; the date itself stays honestly unknown —
    { path: '100MEDIA/IMAG0181.jpg', body: makeJpeg(null, 'htc4'),
      expected: { kind: 'photo', date: null, year: 2011, evidence: 'dir-cohort', assumed: true } },
    // — EXIF and dir-name evidence agree (hand-sorted season subtree exists in real archive) —
    { path: '2013/Лето 2013/DSC01529.JPG', body: makeJpeg('2013:07:04 10:11:12', 'sony1'),
      expected: { kind: 'photo', date: '2013-07-04 10:11:12', evidence: 'exif' } },
    // — hand-sorted subtree, NO exif: dirname is the only evidence (year + season, autumn!) —
    { path: '2013/осень 2013/день рождения.jpg', body: makeJpeg(null, 'bday1'),
      expected: { kind: 'photo', date: null, year: 2013, season: 'осень', evidence: 'dirname' } },
    // — epoch-milliseconds filename (7 895 such files in the real archive) —
    { path: 'Разное/1374250121884.jpg', body: makeJpeg(null, 'epoch1'),
      expected: { kind: 'photo', date: '2013-07-19 18:08:41', evidence: 'filename-epoch' } },
    // — social-network export: 11-char id, no EXIF, no date anywhere → global "прочее" —
    { path: 'Из ВК/6V2qnCITQIE.jpg', body: makeJpeg(null, 'vk1'),
      expected: { kind: 'photo', date: null, evidence: 'none' } },
    // — Android screenshot with full timestamp + app suffix —
    { path: 'скриншоты/Screenshot_2017-05-27-19-34-56-006_com.android.chrome.png', body: makePng('scr1'),
      expected: { kind: 'photo', date: '2017-05-27 19:34:56', evidence: 'filename' } },
    // — WhatsApp date-only name —
    { path: 'Разное/IMG-20160404-WA0001.jpg', body: makeJpeg(null, 'wa1'),
      expected: { kind: 'photo', date: '2016-04-04 00:00:00', dateOnly: true, evidence: 'filename' } },
    // — Cyrillic *extension* (real case: `.без названия`) — media identified by content, not ext —
    { path: 'семейный архив/скан.без названия', body: makeJpeg('2008:12:31 09:00:00', 'cyr1'),
      expected: { kind: 'photo', date: '2008-12-31 09:00:00', evidence: 'exif', mediaByContentOnly: true } },
    // — broken camera clock: EXIF says 1979 → implausible, must be disputed, not trusted —
    { path: 'старое/IMAG0001.jpg', body: makeJpeg('1979:01:01 00:00:03', 'clock1'),
      expected: { kind: 'photo', date: null, evidence: 'exif-implausible', disputed: true } },
    // — a camera whose battery had been out: EXIF says 1 January 00:25, the manufacturer's default,
    //   in a collection whose earliest real photograph is 2008. The shape alone would not be enough
    //   (a New Year photo looks the same), so the guard is the collection's own floor — this file
    //   claims a year the archive has no photography from at all. Owner's decision 2026-07-28.
    { path: 'старое/IMAG0002.jpg', body: makeJpeg('2000:01:01 00:25:13', 'reset1'),
      expected: { kind: 'photo', date: null, evidence: 'exif-reset-clock', disputed: true } },
    // — the SAME shape inside the archive's own era: a real New Year photograph at 00:40 on
    //   1 January 2016. It must survive untouched — the rule may only fire on a proven reset.
    { path: 'Мобилка/новогодняя ночь.jpg', body: makeJpeg('2016:01:01 00:40:12', 'newyear1'),
      expected: { kind: 'photo', date: '2016-01-01 00:40:12', evidence: 'exif' } },
    // — exact duplicates: one shot, three byte-identical copies under different names/dirs —
    { path: '2014/DSC02000.JPG', body: makeJpeg('2014:08:10 12:00:00', 'dup1'),
      expected: { kind: 'photo', date: '2014-08-10 12:00:00', evidence: 'exif', dupGroup: 1 } },
    { path: 'копии/DSC02000.JPG', body: makeJpeg('2014:08:10 12:00:00', 'dup1'),
      expected: { kind: 'photo', date: '2014-08-10 12:00:00', evidence: 'exif', dupGroup: 1 } },
    { path: 'копии/лучшая фотка (копия).jpg', body: makeJpeg('2014:08:10 12:00:00', 'dup1'),
      expected: { kind: 'photo', date: '2014-08-10 12:00:00', evidence: 'exif', dupGroup: 1 } },
    // — video: mvhd creation_time and filename agree —
    { path: 'видео/VID_20161210_100950.mp4', body: makeMp4('2016-12-10T10:09:50Z', 'vid1'),
      expected: { kind: 'video', date: '2016-12-10 10:09:50', evidence: 'filename' } },
    // — video: mvhd only (name carries nothing) —
    { path: 'видео/MOV0001.mp4', body: makeMp4('2018-06-02T15:30:00Z', 'vid2'),
      expected: { kind: 'video', date: '2018-06-02 15:30:00', evidence: 'mvhd-utc' } },
    // — audio (voice note, WhatsApp-style dated name) → <year>/<season>/аудио/ per interview #001 —
    { path: 'голосовые/AUD-20150910-WA0003.ogg', body: makeOgg('aud1'),
      expected: { kind: 'audio', date: '2015-09-10 00:00:00', dateOnly: true, evidence: 'filename' } },
    // — researches/04: a THM sidecar beside its AVI twin. The camera wrote the capture date into
    //   the thumbnail; the AVI itself carries NO container date (RIFF, not ISO-BMFF) and its name
    //   is a bare serial — so the sidecar is the video's only date. 25 real files are in this
    //   shape, all of them stuck at "a year, no season" until this evidence exists.
    { path: 'видео/MVI_0042.avi', body: makeAvi('avi1'),
      expected: { kind: 'video', date: '2012-04-11 20:18:02', evidence: 'sidecar' } },
    //   The thumbnail itself is JUNK by the owner's decision (2026-07-28) — a valid JPEG, but a
    //   160x120 camera artifact, not a photograph: quarantined with provenance, never in the
    //   library, and STILL the source of its video's date.
    { path: 'видео/MVI_0042.THM', body: makeJpegEx({ dateTimeOriginal: '2012:04:11 20:18:02',
        make: 'SONY', model: 'DSC-S3000', width: 160, height: 120, uniq: 'thm1' }),
      expected: { kind: 'junk', date: null, evidence: 'none' } },
    // — an ORPHAN THM (9 of the archive's 34): the video it described is gone. It must pair with
    //   nothing rather than attach itself to a neighbour — the extension is mixed-case on purpose,
    //   since real ones arrive that way and pairing is case-insensitive.
    { path: 'видео/MVI_9999.THM', body: makeJpegEx({ dateTimeOriginal: '2010:09:07 17:10:04',
        make: 'Canon', model: 'Canon PowerShot A580', width: 160, height: 120, uniq: 'thm2' }),
      expected: { kind: 'junk', date: null, evidence: 'none' } },
    // — an XMP sidecar in the full-name convention (`photo.jpg.xmp`, the one form observed), whose
    //   exif:DateTimeOriginal dates a photo that has no metadata of its own.
    { path: 'сканы/скан_без_даты.jpg', body: makeJpeg(null, 'xmp1'),
      expected: { kind: 'photo', date: '2009-08-14 16:20:00', evidence: 'sidecar' } },
    { path: 'сканы/скан_без_даты.jpg.xmp', body: makeXmp({ dateTimeOriginal: '2009-08-14T16:20:00+03:00' }),
      expected: { kind: 'other', date: null, evidence: 'none' } },
    // — an XMP carrying ONLY a save date: it must donate NOTHING (plans/02 §1.1 applied to
    //   sidecars — a sidecar cannot tell a copied capture date from a save time), so its twin
    //   stays honestly undated instead of being shelved into 2014.
    { path: 'сканы/только_правка.jpg', body: makeJpeg(null, 'xmp2'),
      expected: { kind: 'photo', date: null, evidence: 'none' } },
    { path: 'сканы/только_правка.jpg.xmp', body: makeXmp({ modifyDate: '2014-11-20T20:15:00' }),
      expected: { kind: 'other', date: null, evidence: 'none' } },
    // — plans/02 step 1: editor exports whose only date is the editor's SAVE date —
    // (a) the family case, modelled on the owner's real `Безимени-1.jpg`: three GT-I9100 shots,
    //     all 2013, native 3264×2448 — and a Photoshop crop (2280×2448, one native side kept)
    //     saved in Feb 2014 with NO capture date. The save date must NOT shelve it into 2014;
    //     the camera family narrows it to 2013 as a flagged assumption.
    { path: 'фотки с телефона/SAM_1001.jpg', body: makeJpegEx({ dateTimeOriginal: '2013:06:15 10:00:00',
        make: 'SAMSUNG', model: 'GT-I9100', width: 3264, height: 2448, uniq: 'fam1' }),
      expected: { kind: 'photo', date: '2013-06-15 10:00:00', evidence: 'exif' } },
    { path: 'фотки с телефона/SAM_1002.jpg', body: makeJpegEx({ dateTimeOriginal: '2013:07:20 12:30:00',
        make: 'SAMSUNG', model: 'GT-I9100', width: 3264, height: 2448, uniq: 'fam2' }),
      expected: { kind: 'photo', date: '2013-07-20 12:30:00', evidence: 'exif' } },
    { path: 'фотки с телефона/SAM_1003.jpg', body: makeJpegEx({ dateTimeOriginal: '2013:08:05 18:45:00',
        make: 'SAMSUNG', model: 'GT-I9100', width: 3264, height: 2448, uniq: 'fam3' }),
      expected: { kind: 'photo', date: '2013-08-05 18:45:00', evidence: 'exif' } },
    { path: 'фотки с телефона/правка.jpg', body: makeJpegEx({ software: 'Adobe Photoshop CS3 Windows',
        dateTime: '2014:02:09 11:09:09', width: 2280, height: 2448, uniq: 'fam4' }),
      expected: { kind: 'photo', date: null, year: 2013, evidence: 'family', assumed: true } },
    // (b) the exact-original case: the editor wrote XMP DerivedFrom → the original's DocumentID,
    //     so the export inherits the original's REAL capture date, never its own save date.
    { path: 'обработанное/оригинал.jpg', body: makeJpegEx({ dateTimeOriginal: '2012:05:01 10:00:00',
        make: 'SONY', model: 'DSC-W55', width: 3072, height: 2304,
        documentId: 'uuid:KPOT-ORIG-0001', uniq: 'der1' }),
      expected: { kind: 'photo', date: '2012-05-01 10:00:00', evidence: 'exif' } },
    { path: 'обработанное/экспорт.jpg', body: makeJpegEx({ software: 'Adobe Photoshop CS2 Windows',
        dateTime: '2015:03:03 09:00:00', width: 1200, height: 900,
        derivedFromDocumentId: 'uuid:KPOT-ORIG-0001', uniq: 'der2' }),
      expected: { kind: 'photo', date: '2012-05-01 10:00:00', evidence: 'derived-original' } },
    // (c) the honest-ignorance case: a Picasa save with no capture date, no matching family,
    //     no original — the save date is only a ceiling; the file goes to ПРОЧЕЕ, never to 2014.
    { path: 'обработанное/безымянный.jpg', body: makeJpegEx({ software: 'Picasa',
        dateTime: '2014:11:20 20:15:00', width: 1000, height: 750, uniq: 'edt1' }),
      expected: { kind: 'photo', date: null, evidence: 'editor-upper-bound', disputed: true } },
    // (d) plans/02 §Шаг 2 — the original found BY ITS PIXELS. Four originals of one camera, one per
    //     year, so `family` narrows nothing; the Photoshop crop keeps the full sensor height and
    //     70% of the width — the geometry researches/05 measured on the owner's own export. Only a
    //     pixel comparison can say WHICH of the four it came from, and it must say so decisively.
    { path: '101MEDIA/DSC00101.JPG', body: makeJpegEx({ dateTimeOriginal: '2011:05:04 09:12:00',
        make: 'SONY', model: 'DSC-HX9V', pixels: shots.a, uniq: 'pix1' }),
      expected: { kind: 'photo', date: '2011-05-04 09:12:00', evidence: 'exif' } },
    { path: '101MEDIA/DSC00102.JPG', body: makeJpegEx({ dateTimeOriginal: '2012:06:15 12:30:00',
        make: 'SONY', model: 'DSC-HX9V', pixels: shots.b, uniq: 'pix2' }),
      expected: { kind: 'photo', date: '2012-06-15 12:30:00', evidence: 'exif' } },
    { path: '101MEDIA/DSC00103.JPG', body: makeJpegEx({ dateTimeOriginal: '2013:07:20 18:05:00',
        make: 'SONY', model: 'DSC-HX9V', pixels: shots.c, uniq: 'pix3' }),
      expected: { kind: 'photo', date: '2013-07-20 18:05:00', evidence: 'exif' } },
    { path: '101MEDIA/DSC00104.JPG', body: makeJpegEx({ dateTimeOriginal: '2014:08:05 07:40:00',
        make: 'SONY', model: 'DSC-HX9V', pixels: shots.d, uniq: 'pix4' }),
      expected: { kind: 'photo', date: '2014-08-05 07:40:00', evidence: 'exif' } },
    { path: '101MEDIA/правка кадра.jpg', body: makeJpegEx({ software: 'Adobe Photoshop CS3 Windows',
        dateTime: '2015:03:03 09:00:00', pixels: cropPixels(shots.b), uniq: 'pix5' }),
      expected: { kind: 'photo', date: '2012-06-15 12:30:00', evidence: 'pixel-original',
                  original: '101MEDIA/DSC00102.JPG' } },
    // (e) the same shape, but the original is NOT in the tree: no candidate may win decisively, so
    //     the file must stay honestly undated. This is the guard against the failure mode
    //     researches/05 §5 measured — a look-alike winning a global threshold.
    { path: '101MEDIA/правка чужого.jpg', body: makeJpegEx({ software: 'Picasa',
        dateTime: '2015:04:04 10:00:00', pixels: cropPixels(shots.lost), uniq: 'pix6' }),
      expected: { kind: 'photo', date: null, evidence: 'editor-upper-bound', disputed: true } },
    // — junk → quarantine with provenance (interview #001 Q4 = C) —
    { path: '100MEDIA/Thumbs.db', body: text('fake thumbs db'),
      expected: { kind: 'junk', date: null, evidence: 'none' } },
    { path: 'Мобилка/.nomedia', body: text(''),
      expected: { kind: 'junk', date: null, evidence: 'none' } },
    // — non-media, non-junk → stays in place + report (interview #001 Q5 = A) —
    { path: 'доки/письмо.docx', body: text('fake docx bytes'),
      expected: { kind: 'other', date: null, evidence: 'none' } },
    { path: 'доки/заметка.txt', body: text('просто заметка'),
      expected: { kind: 'other', date: null, evidence: 'none' } },
  ];
}

// Files whose filesystem mtime is planted to the same fake "bulk copy day" — a real-archive artifact
// (18 656 files "modified" on one day). Their mtime must be detected as a spike and discounted.
const COPY_SPIKE_PATHS = new Set([
  'Из ВК/6V2qnCITQIE.jpg', 'Разное/1374250121884.jpg', 'Мобилка/IMG_20140121_183801.jpg',
]);

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Create the fixture tree under `root` (created if missing) and write `expected.json` into it.
 * @returns {Promise<object>} the manifest object
 */
export async function makeFixtureTree(root) {
  const cases = catalog();
  for (const c of cases) {
    const abs = join(root, ...c.path.split('/'));
    await mkdir(dirname(abs), { recursive: true });
    await writeFile(abs, c.body);
    // Plant a deterministic mtime: spike files get the fake copy day; the rest get a fixed old date,
    // so nothing depends on the machine clock at generation time.
    const mtime = COPY_SPIKE_PATHS.has(c.path) ? COPY_SPIKE_MTIME : FIXED_MTIME;
    await utimes(abs, mtime, mtime);
  }
  const manifest = {
    fixtureVersion: FIXTURE_VERSION,
    copySpikeMtime: COPY_SPIKE_MTIME.toISOString(),
    files: cases.map(c => ({ path: c.path, size: c.body.length, expected: c.expected,
                             mtimeSpiked: COPY_SPIKE_PATHS.has(c.path) })),
  };
  const manifestPath = join(root, 'expected.json');
  await writeFile(manifestPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  // The ground-truth manifest lives INSIDE the tree, so the scan sees it as one more file — and
  // until 2026-07-29 it was the single thing here that carried a wall-clock mtime, which made this
  // generator's own "deterministic" claim false by exactly one row. Found by a golden-snapshot
  // harness that was self-tested first: two captures of UNCHANGED code differed in this one number.
  await utimes(manifestPath, FIXED_MTIME, FIXED_MTIME);
  return manifest;
}

// CLI entry: node tests/fixtures/make.mjs <targetDir>
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const target = process.argv[2];
  if (!target) { console.error('usage: node tests/fixtures/make.mjs <targetDir>'); process.exit(2); }
  const m = await makeFixtureTree(target);
  console.log(`fixture tree v${m.fixtureVersion}: ${m.files.length} files planted in ${target}`);
}
