// tests/fixtures/make.mjs — synthetic messy-tree generator.
// [TESTED: 2026-07-24 · npm test 5/5 green (tests/fixtures.test.mjs) + CLI smoke run into scratchpad]
//
// Builds a deterministic "chaotic archive" fixture tree with KNOWN-CORRECT answers, so every later
// KPOT phase (scan/meta/dedupe/plan/apply) can be verified objectively without a human and without
// ever touching a real archive. The case catalog mirrors the real-chaos survey in
// researches/02_real_archive_survey.md: date-in-filename patterns, epoch-named files, camera-serial
// names needing EXIF, social-export names with no evidence, "+"-twins, Cyrillic names (including a
// Cyrillic *extension*), an already-hand-sorted year/season subtree, junk files, non-media files,
// audio, video with an mvhd date, a broken-camera-clock date, and byte-identical duplicates.
//
// Every generated byte is fixed (no randomness, no clock reads) — two runs produce identical trees.
// Alongside the tree it writes `expected.json`: the ground-truth manifest tests assert against.
//
// Usage:  node tests/fixtures/make.mjs <targetDir>          (CLI)
//         const m = await makeFixtureTree(dir)              (from tests)

import { mkdir, writeFile, utimes } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import process from 'node:process';

/** Version stamp of the fixture catalog — bump when cases change so stale trees are detectable. */
export const FIXTURE_VERSION = 3; // v3 (2026-07-27): +7 cases — the plans/02 editor-export classes
                                  // (family geometry, XMP DerivedFrom original, honest ПРОЧЕЕ)

/** Seconds between the QuickTime epoch (1904-01-01) and the Unix epoch (1970-01-01). */
const QT_EPOCH_OFFSET = 2082844800;

/** A fixed "bulk copy day" mtime planted on files whose filesystem time must NOT be trusted. */
const COPY_SPIKE_MTIME = new Date('2023-05-15T12:00:00Z');

// ---------------------------------------------------------------------------
// Binary builders — minimal but magic-correct file bodies.
// They are as small as honesty allows: metadata segments are real and parseable; pixel/sound data
// is NOT decodable (KPOT never decodes pixels — see researches/01_prior_art.md §1).
// ---------------------------------------------------------------------------

/**
 * Minimal JPEG: SOI + optional APP1/Exif (with a real TIFF IFD carrying DateTimeOriginal) +
 * a COM segment holding `uniq` (differentiates file bytes) + EOI.
 * @param {string|null} exifDate  "YYYY:MM:DD HH:MM:SS" or null for no EXIF
 * @param {string} uniq           unique padding so distinct files are not accidental byte-duplicates
 */
export function makeJpeg(exifDate, uniq) {
  const parts = [Buffer.from([0xFF, 0xD8])]; // SOI
  if (exifDate) {
    // TIFF (little-endian): IFD0 with one entry → ExifIFD; ExifIFD with one entry → DateTimeOriginal.
    const tiff = Buffer.alloc(64);
    tiff.write('II', 0, 'ascii'); tiff.writeUInt16LE(42, 2); tiff.writeUInt32LE(8, 4);
    tiff.writeUInt16LE(1, 8);                              // IFD0: 1 entry
    tiff.writeUInt16LE(0x8769, 10); tiff.writeUInt16LE(4, 12); // ExifIFD pointer, LONG
    tiff.writeUInt32LE(1, 14); tiff.writeUInt32LE(26, 18);
    tiff.writeUInt32LE(0, 22);                             // next IFD: none
    tiff.writeUInt16LE(1, 26);                             // ExifIFD: 1 entry
    tiff.writeUInt16LE(0x9003, 28); tiff.writeUInt16LE(2, 30); // DateTimeOriginal, ASCII
    tiff.writeUInt32LE(20, 32); tiff.writeUInt32LE(44, 36);
    tiff.writeUInt32LE(0, 40);                             // next IFD: none
    tiff.write(exifDate + '\0', 44, 'ascii');              // 20 bytes incl. NUL
    const payload = Buffer.concat([Buffer.from('Exif\0\0', 'ascii'), tiff]);
    const app1 = Buffer.alloc(4);
    app1.writeUInt16BE(0xFFE1, 0); app1.writeUInt16BE(payload.length + 2, 2);
    parts.push(app1, payload);
  }
  const comText = Buffer.from('kpot-fixture:' + uniq, 'ascii'); // COM segment = per-file uniqueness
  const com = Buffer.alloc(4);
  com.writeUInt16BE(0xFFFE, 0); com.writeUInt16BE(comText.length + 2, 2);
  parts.push(com, comText, Buffer.from([0xFF, 0xD9])); // EOI
  return Buffer.concat(parts);
}

/**
 * Minimal MP4: `ftyp` + `moov/mvhd` with a real creation_time (QuickTime epoch, UTC).
 * @param {string|null} isoUtc  e.g. "2016-12-10T10:09:50Z", or null for creation_time = 0 (unset)
 */
export function makeMp4(isoUtc, uniq) {
  const ftyp = Buffer.alloc(16);
  ftyp.writeUInt32BE(16, 0); ftyp.write('ftyp', 4, 'ascii');
  ftyp.write('isom', 8, 'ascii'); ftyp.writeUInt32BE(0, 12);
  const mvhd = Buffer.alloc(108);
  mvhd.writeUInt32BE(108, 0); mvhd.write('mvhd', 4, 'ascii'); // version 0, flags 0
  const secs = isoUtc ? Math.floor(Date.parse(isoUtc) / 1000) + QT_EPOCH_OFFSET : 0;
  mvhd.writeUInt32BE(secs, 12);        // creation_time
  mvhd.writeUInt32BE(secs, 16);        // modification_time
  mvhd.writeUInt32BE(1000, 20);        // timescale
  mvhd.writeUInt32BE(0, 24);           // duration
  mvhd.writeUInt32BE(0x00010000, 28);  // rate 1.0
  mvhd.writeUInt16BE(0x0100, 32);      // volume 1.0
  const moov = Buffer.alloc(8);
  moov.writeUInt32BE(8 + 108, 0); moov.write('moov', 4, 'ascii');
  // `free` box carries per-file uniqueness (real MP4s allow it anywhere top-level)
  const uniqBytes = Buffer.from('kpot-fixture:' + uniq, 'ascii');
  const free = Buffer.alloc(8);
  free.writeUInt32BE(8 + uniqBytes.length, 0); free.write('free', 4, 'ascii');
  return Buffer.concat([ftyp, moov, mvhd, free, uniqBytes]);
}

/**
 * Full-featured JPEG for the plans/02 editor-export cases: a real little-endian TIFF with a
 * multi-entry IFD0 (Make/Model/Software/DateTime) and an optional ExifIFD (DateTimeOriginal),
 * an optional XMP APP1 packet (DocumentID / DerivedFrom — the Photoshop identity chain), and an
 * optional SOF0 carrying real pixel dimensions (what family geometry reads). Every offset is
 * computed, every segment parseable — "the date is really in the file" stays assertable.
 *
 * @param {{dateTimeOriginal?: string|null, dateTime?: string|null, software?: string|null,
 *          make?: string|null, model?: string|null, width?: number|null, height?: number|null,
 *          documentId?: string|null, derivedFromDocumentId?: string|null, uniq: string}} opts
 */
export function makeJpegEx({ dateTimeOriginal = null, dateTime = null, software = null,
                             make = null, model = null, width = null, height = null,
                             documentId = null, derivedFromDocumentId = null, uniq }) {
  const parts = [Buffer.from([0xFF, 0xD8])]; // SOI

  // --- APP1/Exif: IFD0 entries in ascending tag order (TIFF requirement) ---
  const ifd0 = [];
  if (make) ifd0.push({ tag: 0x010F, value: make });
  if (model) ifd0.push({ tag: 0x0110, value: model });
  if (software) ifd0.push({ tag: 0x0131, value: software });
  if (dateTime) ifd0.push({ tag: 0x0132, value: dateTime });
  const hasExifIfd = Boolean(dateTimeOriginal);
  if (ifd0.length > 0 || hasExifIfd) {
    const n0 = ifd0.length + (hasExifIfd ? 1 : 0);       // +1 for the ExifIFD pointer entry
    const ifd0Start = 8;
    const exifIfdStart = ifd0Start + 2 + n0 * 12 + 4;
    const exifIfdSize = hasExifIfd ? 2 + 1 * 12 + 4 : 0;
    const dataStart = exifIfdStart + exifIfdSize;
    const asciiBytes = (v) => v.length + 1; // incl. NUL
    const dataTotal = ifd0.reduce((s, e) => s + (asciiBytes(e.value) > 4 ? asciiBytes(e.value) : 0), 0)
      + (hasExifIfd ? asciiBytes(dateTimeOriginal) : 0);
    const tiff = Buffer.alloc(dataStart + dataTotal);
    tiff.write('II', 0, 'ascii'); tiff.writeUInt16LE(42, 2); tiff.writeUInt32LE(ifd0Start, 4);
    let dataOff = dataStart;
    const writeAscii = (at, tag, value) => {
      const bytes = asciiBytes(value);
      tiff.writeUInt16LE(tag, at); tiff.writeUInt16LE(2, at + 2); // type ASCII
      tiff.writeUInt32LE(bytes, at + 4);
      if (bytes <= 4) { tiff.write(value + '\0', at + 8, 'ascii'); }
      else { tiff.writeUInt32LE(dataOff, at + 8); tiff.write(value + '\0', dataOff, 'ascii'); dataOff += bytes; }
    };
    tiff.writeUInt16LE(n0, ifd0Start);
    ifd0.forEach((e, i) => writeAscii(ifd0Start + 2 + i * 12, e.tag, e.value));
    if (hasExifIfd) {
      const at = ifd0Start + 2 + ifd0.length * 12;       // the last IFD0 entry: the ExifIFD pointer
      tiff.writeUInt16LE(0x8769, at); tiff.writeUInt16LE(4, at + 2); // type LONG
      tiff.writeUInt32LE(1, at + 4); tiff.writeUInt32LE(exifIfdStart, at + 8);
    }
    tiff.writeUInt32LE(0, ifd0Start + 2 + n0 * 12);      // IFD0: next IFD = none
    if (hasExifIfd) {
      tiff.writeUInt16LE(1, exifIfdStart);               // ExifIFD: 1 entry
      writeAscii(exifIfdStart + 2, 0x9003, dateTimeOriginal); // DateTimeOriginal
      tiff.writeUInt32LE(0, exifIfdStart + 2 + 12);      // next IFD: none
    }
    const payload = Buffer.concat([Buffer.from('Exif\0\0', 'ascii'), tiff]);
    const app1 = Buffer.alloc(4);
    app1.writeUInt16BE(0xFFE1, 0); app1.writeUInt16BE(payload.length + 2, 2);
    parts.push(app1, payload);
  }

  // --- APP1/XMP: the identity chain Photoshop-class editors write ---
  if (documentId || derivedFromDocumentId) {
    const xml = '<x:xmpmeta xmlns:x="adobe:ns:meta/">'
      + '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
      + '<rdf:Description rdf:about="" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"'
      + ' xmlns:stRef="http://ns.adobe.com/xap/1.0/sType/ResourceRef#"'
      + (documentId ? ` xmpMM:DocumentID="${documentId}"` : '')
      + '>'
      + (derivedFromDocumentId
        ? `<xmpMM:DerivedFrom stRef:documentID="${derivedFromDocumentId}"/>` : '')
      + '</rdf:Description></rdf:RDF></x:xmpmeta>';
    const payload = Buffer.concat([
      Buffer.from('http://ns.adobe.com/xap/1.0/\0', 'ascii'), Buffer.from(xml, 'utf8')]);
    const app1 = Buffer.alloc(4);
    app1.writeUInt16BE(0xFFE1, 0); app1.writeUInt16BE(payload.length + 2, 2);
    parts.push(app1, payload);
  }

  // --- SOF0: real pixel dimensions (family geometry evidence reads these) ---
  if (width && height) {
    const sof = Buffer.alloc(19);
    sof.writeUInt16BE(0xFFC0, 0); sof.writeUInt16BE(17, 2);
    sof[4] = 8; sof.writeUInt16BE(height, 5); sof.writeUInt16BE(width, 7); sof[9] = 3;
    sof.set([1, 0x22, 0, 2, 0x11, 1, 3, 0x11, 1], 10);
    parts.push(sof);
  }

  const comText = Buffer.from('kpot-fixture:' + uniq, 'ascii'); // COM segment = per-file uniqueness
  const com = Buffer.alloc(4);
  com.writeUInt16BE(0xFFFE, 0); com.writeUInt16BE(comText.length + 2, 2);
  parts.push(com, comText, Buffer.from([0xFF, 0xD9])); // EOI
  return Buffer.concat(parts);
}

/** Minimal PNG: real signature + IHDR/IEND shells (CRCs zeroed — magic-detection fixtures only). */
export function makePng(uniq) {
  const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  const ihdr = Buffer.alloc(25); // len(4) 'IHDR' 13-byte body + zero CRC
  ihdr.writeUInt32BE(13, 0); ihdr.write('IHDR', 4, 'ascii');
  ihdr.writeUInt32BE(1, 8); ihdr.writeUInt32BE(1, 12); ihdr[16] = 8; ihdr[17] = 0;
  const text = Buffer.from('kpot-fixture:' + uniq, 'ascii');
  const iend = Buffer.alloc(12); iend.write('IEND', 4, 'ascii');
  return Buffer.concat([sig, ihdr, text, iend]);
}

/** Minimal OGG: real 'OggS' magic + uniqueness padding. */
export function makeOgg(uniq) {
  return Buffer.concat([Buffer.from('OggS\0\0\0\0', 'ascii'), Buffer.from('kpot-fixture:' + uniq)]);
}

const text = (s) => Buffer.from(s, 'utf8');

// ---------------------------------------------------------------------------
// The case catalog — one entry per planted file.
// expected.date is the GROUND-TRUTH capture date ("YYYY-MM-DD HH:MM:SS" local, or null = undatable);
// expected.evidence names the strongest evidence KPOT is supposed to find it by.
// ---------------------------------------------------------------------------

/** @returns the full planted-case list (path separators are '/', converted on write) */
export function catalog() {
  return [
    // — date in the filename (Android camera convention) —
    { path: 'Мобилка/IMG_20140121_183801.jpg', body: makeJpeg(null, 'and1'),
      expected: { kind: 'photo', date: '2014-01-21 18:38:01', evidence: 'filename' } },
    // — "+"-twin pair: one char apart, different bytes, must NOT be merged as duplicates —
    { path: 'Мобилка/IMG_20140121_184626.jpg', body: makeJpeg(null, 'twinA'),
      expected: { kind: 'photo', date: '2014-01-21 18:46:26', evidence: 'filename', twin: 'plus-pair' } },
    { path: 'Мобилка/IMG_20140121_184626+.jpg', body: makeJpeg(null, 'twinB'),
      expected: { kind: 'photo', date: '2014-01-21 18:46:26', evidence: 'filename', twin: 'plus-pair' } },
    // — camera serial names, EXIF is the only evidence; three confident 2011 files make this
    //   device-dump dir a cohort for the EXIF-less neighbor below (owner decision 2026-07-24) —
    { path: '100MEDIA/IMAG0178.jpg', body: makeJpeg('2011:03:04 09:15:00', 'htc2'),
      expected: { kind: 'photo', date: '2011-03-04 09:15:00', evidence: 'exif' } },
    { path: '100MEDIA/IMAG0179.jpg', body: makeJpeg('2011:03:05 11:02:10', 'htc3'),
      expected: { kind: 'photo', date: '2011-03-05 11:02:10', evidence: 'exif' } },
    { path: '100MEDIA/IMAG0180.jpg', body: makeJpeg('2011:03:05 14:20:33', 'htc1'),
      expected: { kind: 'photo', date: '2011-03-05 14:20:33', evidence: 'exif' } },
    // — EXIF-less file among confidently-dated neighbors → ASSUMED year via dir cohort, must be
    //   marked assumed and surfaced to the owner; the date itself stays honestly unknown —
    { path: '100MEDIA/IMAG0181.jpg', body: makeJpeg(null, 'htc4'),
      expected: { kind: 'photo', date: null, year: 2011, evidence: 'dir-cohort', assumed: true } },
    // — EXIF and dir-name evidence agree (hand-sorted season subtree exists in real archive) —
    { path: '2013/Лето 2013/DSC01529.JPG', body: makeJpeg('2013:07:04 10:11:12', 'sony1'),
      expected: { kind: 'photo', date: '2013-07-04 10:11:12', evidence: 'exif' } },
    // — hand-sorted subtree, NO exif: dirname is the only evidence (year + season, autumn!) —
    { path: '2013/осень 2013/день рождения.jpg', body: makeJpeg(null, 'bday1'),
      expected: { kind: 'photo', date: null, year: 2013, season: 'осень', evidence: 'dirname' } },
    // — epoch-milliseconds filename (7 895 such files in the real archive) —
    { path: 'Разное/1374250121884.jpg', body: makeJpeg(null, 'epoch1'),
      expected: { kind: 'photo', date: '2013-07-19 18:08:41', evidence: 'filename-epoch' } },
    // — social-network export: 11-char id, no EXIF, no date anywhere → global "прочее" —
    { path: 'Из ВК/6V2qnCITQIE.jpg', body: makeJpeg(null, 'vk1'),
      expected: { kind: 'photo', date: null, evidence: 'none' } },
    // — Android screenshot with full timestamp + app suffix —
    { path: 'скриншоты/Screenshot_2017-05-27-19-34-56-006_com.android.chrome.png', body: makePng('scr1'),
      expected: { kind: 'photo', date: '2017-05-27 19:34:56', evidence: 'filename' } },
    // — WhatsApp date-only name —
    { path: 'Разное/IMG-20160404-WA0001.jpg', body: makeJpeg(null, 'wa1'),
      expected: { kind: 'photo', date: '2016-04-04 00:00:00', dateOnly: true, evidence: 'filename' } },
    // — Cyrillic *extension* (real case: `.без названия`) — media identified by content, not ext —
    { path: 'семейный архив/скан.без названия', body: makeJpeg('2008:12:31 09:00:00', 'cyr1'),
      expected: { kind: 'photo', date: '2008-12-31 09:00:00', evidence: 'exif', mediaByContentOnly: true } },
    // — broken camera clock: EXIF says 1979 → implausible, must be disputed, not trusted —
    { path: 'старое/IMAG0001.jpg', body: makeJpeg('1979:01:01 00:00:03', 'clock1'),
      expected: { kind: 'photo', date: null, evidence: 'exif-implausible', disputed: true } },
    // — exact duplicates: one shot, three byte-identical copies under different names/dirs —
    { path: '2014/DSC02000.JPG', body: makeJpeg('2014:08:10 12:00:00', 'dup1'),
      expected: { kind: 'photo', date: '2014-08-10 12:00:00', evidence: 'exif', dupGroup: 1 } },
    { path: 'копии/DSC02000.JPG', body: makeJpeg('2014:08:10 12:00:00', 'dup1'),
      expected: { kind: 'photo', date: '2014-08-10 12:00:00', evidence: 'exif', dupGroup: 1 } },
    { path: 'копии/лучшая фотка (копия).jpg', body: makeJpeg('2014:08:10 12:00:00', 'dup1'),
      expected: { kind: 'photo', date: '2014-08-10 12:00:00', evidence: 'exif', dupGroup: 1 } },
    // — video: mvhd creation_time and filename agree —
    { path: 'видео/VID_20161210_100950.mp4', body: makeMp4('2016-12-10T10:09:50Z', 'vid1'),
      expected: { kind: 'video', date: '2016-12-10 10:09:50', evidence: 'filename' } },
    // — video: mvhd only (name carries nothing) —
    { path: 'видео/MOV0001.mp4', body: makeMp4('2018-06-02T15:30:00Z', 'vid2'),
      expected: { kind: 'video', date: '2018-06-02 15:30:00', evidence: 'mvhd-utc' } },
    // — audio (voice note, WhatsApp-style dated name) → <year>/<season>/аудио/ per interview #001 —
    { path: 'голосовые/AUD-20150910-WA0003.ogg', body: makeOgg('aud1'),
      expected: { kind: 'audio', date: '2015-09-10 00:00:00', dateOnly: true, evidence: 'filename' } },
    // — plans/02 step 1: editor exports whose only date is the editor's SAVE date —
    // (a) the family case, modelled on the owner's real `Безимени-1.jpg`: three GT-I9100 shots,
    //     all 2013, native 3264×2448 — and a Photoshop crop (2280×2448, one native side kept)
    //     saved in Feb 2014 with NO capture date. The save date must NOT shelve it into 2014;
    //     the camera family narrows it to 2013 as a flagged assumption.
    { path: 'фотки с телефона/SAM_1001.jpg', body: makeJpegEx({ dateTimeOriginal: '2013:06:15 10:00:00',
        make: 'SAMSUNG', model: 'GT-I9100', width: 3264, height: 2448, uniq: 'fam1' }),
      expected: { kind: 'photo', date: '2013-06-15 10:00:00', evidence: 'exif' } },
    { path: 'фотки с телефона/SAM_1002.jpg', body: makeJpegEx({ dateTimeOriginal: '2013:07:20 12:30:00',
        make: 'SAMSUNG', model: 'GT-I9100', width: 3264, height: 2448, uniq: 'fam2' }),
      expected: { kind: 'photo', date: '2013-07-20 12:30:00', evidence: 'exif' } },
    { path: 'фотки с телефона/SAM_1003.jpg', body: makeJpegEx({ dateTimeOriginal: '2013:08:05 18:45:00',
        make: 'SAMSUNG', model: 'GT-I9100', width: 3264, height: 2448, uniq: 'fam3' }),
      expected: { kind: 'photo', date: '2013-08-05 18:45:00', evidence: 'exif' } },
    { path: 'фотки с телефона/правка.jpg', body: makeJpegEx({ software: 'Adobe Photoshop CS3 Windows',
        dateTime: '2014:02:09 11:09:09', width: 2280, height: 2448, uniq: 'fam4' }),
      expected: { kind: 'photo', date: null, year: 2013, evidence: 'family', assumed: true } },
    // (b) the exact-original case: the editor wrote XMP DerivedFrom → the original's DocumentID,
    //     so the export inherits the original's REAL capture date, never its own save date.
    { path: 'обработанное/оригинал.jpg', body: makeJpegEx({ dateTimeOriginal: '2012:05:01 10:00:00',
        make: 'SONY', model: 'DSC-W55', width: 3072, height: 2304,
        documentId: 'uuid:KPOT-ORIG-0001', uniq: 'der1' }),
      expected: { kind: 'photo', date: '2012-05-01 10:00:00', evidence: 'exif' } },
    { path: 'обработанное/экспорт.jpg', body: makeJpegEx({ software: 'Adobe Photoshop CS2 Windows',
        dateTime: '2015:03:03 09:00:00', width: 1200, height: 900,
        derivedFromDocumentId: 'uuid:KPOT-ORIG-0001', uniq: 'der2' }),
      expected: { kind: 'photo', date: '2012-05-01 10:00:00', evidence: 'derived-original' } },
    // (c) the honest-ignorance case: a Picasa save with no capture date, no matching family,
    //     no original — the save date is only a ceiling; the file goes to ПРОЧЕЕ, never to 2014.
    { path: 'обработанное/безымянный.jpg', body: makeJpegEx({ software: 'Picasa',
        dateTime: '2014:11:20 20:15:00', width: 1000, height: 750, uniq: 'edt1' }),
      expected: { kind: 'photo', date: null, evidence: 'editor-upper-bound', disputed: true } },
    // — junk → quarantine with provenance (interview #001 Q4 = C) —
    { path: '100MEDIA/Thumbs.db', body: text('fake thumbs db'),
      expected: { kind: 'junk', date: null, evidence: 'none' } },
    { path: 'Мобилка/.nomedia', body: text(''),
      expected: { kind: 'junk', date: null, evidence: 'none' } },
    // — non-media, non-junk → stays in place + report (interview #001 Q5 = A) —
    { path: 'доки/письмо.docx', body: text('fake docx bytes'),
      expected: { kind: 'other', date: null, evidence: 'none' } },
    { path: 'доки/заметка.txt', body: text('просто заметка'),
      expected: { kind: 'other', date: null, evidence: 'none' } },
  ];
}

// Files whose filesystem mtime is planted to the same fake "bulk copy day" — a real-archive artifact
// (18 656 files "modified" on one day). Their mtime must be detected as a spike and discounted.
const COPY_SPIKE_PATHS = new Set([
  'Из ВК/6V2qnCITQIE.jpg', 'Разное/1374250121884.jpg', 'Мобилка/IMG_20140121_183801.jpg',
]);

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Create the fixture tree under `root` (created if missing) and write `expected.json` into it.
 * @returns {Promise<object>} the manifest object
 */
export async function makeFixtureTree(root) {
  const cases = catalog();
  for (const c of cases) {
    const abs = join(root, ...c.path.split('/'));
    await mkdir(dirname(abs), { recursive: true });
    await writeFile(abs, c.body);
    // Plant a deterministic mtime: spike files get the fake copy day; the rest get a fixed old date,
    // so nothing depends on the machine clock at generation time.
    const mtime = COPY_SPIKE_PATHS.has(c.path) ? COPY_SPIKE_MTIME : new Date('2015-01-01T00:00:00Z');
    await utimes(abs, mtime, mtime);
  }
  const manifest = {
    fixtureVersion: FIXTURE_VERSION,
    copySpikeMtime: COPY_SPIKE_MTIME.toISOString(),
    files: cases.map(c => ({ path: c.path, size: c.body.length, expected: c.expected,
                             mtimeSpiked: COPY_SPIKE_PATHS.has(c.path) })),
  };
  await writeFile(join(root, 'expected.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  return manifest;
}

// CLI entry: node tests/fixtures/make.mjs <targetDir>
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const target = process.argv[2];
  if (!target) { console.error('usage: node tests/fixtures/make.mjs <targetDir>'); process.exit(2); }
  const m = await makeFixtureTree(target);
  console.log(`fixture tree v${m.fixtureVersion}: ${m.files.length} files planted in ${target}`);
}
