// tests/fixtures/make.mjs — synthetic messy-tree generator.
// [TESTED: 2026-07-24 · npm test 5/5 green (tests/fixtures.test.mjs) + CLI smoke run into scratchpad]
//
// Builds a deterministic "chaotic archive" fixture tree with KNOWN-CORRECT answers, so every later
// KPOT phase (scan/meta/dedupe/plan/apply) can be verified objectively without a human and without
// ever touching a real archive. The case catalog mirrors the real-chaos survey in
// researches/02_real_archive_survey.md: date-in-filename patterns, epoch-named files, camera-serial
// names needing EXIF, social-export names with no evidence, "+"-twins, Cyrillic names (including a
// Cyrillic *extension*), an already-hand-sorted year/season subtree, junk files, non-media files,
// audio, video with an mvhd date, a broken-camera-clock date, and byte-identical duplicates.
//
// Every generated byte is fixed (no randomness, no clock reads) — two runs produce identical trees.
// Alongside the tree it writes `expected.json`: the ground-truth manifest tests assert against.
//
// Usage:  node tests/fixtures/make.mjs <targetDir>          (CLI)
//         const m = await makeFixtureTree(dir)              (from tests)

import { mkdir, writeFile, utimes } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import process from 'node:process';

/** Version stamp of the fixture catalog — bump when cases change so stale trees are detectable. */
export const FIXTURE_VERSION = 1;

/** Seconds between the QuickTime epoch (1904-01-01) and the Unix epoch (1970-01-01). */
const QT_EPOCH_OFFSET = 2082844800;

/** A fixed "bulk copy day" mtime planted on files whose filesystem time must NOT be trusted. */
const COPY_SPIKE_MTIME = new Date('2023-05-15T12:00:00Z');

// ---------------------------------------------------------------------------
// Binary builders — minimal but magic-correct file bodies.
// They are as small as honesty allows: metadata segments are real and parseable; pixel/sound data
// is NOT decodable (KPOT never decodes pixels — see researches/01_prior_art.md §1).
// ---------------------------------------------------------------------------

/**
 * Minimal JPEG: SOI + optional APP1/Exif (with a real TIFF IFD carrying DateTimeOriginal) +
 * a COM segment holding `uniq` (differentiates file bytes) + EOI.
 * @param {string|null} exifDate  "YYYY:MM:DD HH:MM:SS" or null for no EXIF
 * @param {string} uniq           unique padding so distinct files are not accidental byte-duplicates
 */
export function makeJpeg(exifDate, uniq) {
  const parts = [Buffer.from([0xFF, 0xD8])]; // SOI
  if (exifDate) {
    // TIFF (little-endian): IFD0 with one entry → ExifIFD; ExifIFD with one entry → DateTimeOriginal.
    const tiff = Buffer.alloc(64);
    tiff.write('II', 0, 'ascii'); tiff.writeUInt16LE(42, 2); tiff.writeUInt32LE(8, 4);
    tiff.writeUInt16LE(1, 8);                              // IFD0: 1 entry
    tiff.writeUInt16LE(0x8769, 10); tiff.writeUInt16LE(4, 12); // ExifIFD pointer, LONG
    tiff.writeUInt32LE(1, 14); tiff.writeUInt32LE(26, 18);
    tiff.writeUInt32LE(0, 22);                             // next IFD: none
    tiff.writeUInt16LE(1, 26);                             // ExifIFD: 1 entry
    tiff.writeUInt16LE(0x9003, 28); tiff.writeUInt16LE(2, 30); // DateTimeOriginal, ASCII
    tiff.writeUInt32LE(20, 32); tiff.writeUInt32LE(44, 36);
    tiff.writeUInt32LE(0, 40);                             // next IFD: none
    tiff.write(exifDate + '\0', 44, 'ascii');              // 20 bytes incl. NUL
    const payload = Buffer.concat([Buffer.from('Exif\0\0', 'ascii'), tiff]);
    const app1 = Buffer.alloc(4);
    app1.writeUInt16BE(0xFFE1, 0); app1.writeUInt16BE(payload.length + 2, 2);
    parts.push(app1, payload);
  }
  const comText = Buffer.from('kpot-fixture:' + uniq, 'ascii'); // COM segment = per-file uniqueness
  const com = Buffer.alloc(4);
  com.writeUInt16BE(0xFFFE, 0); com.writeUInt16BE(comText.length + 2, 2);
  parts.push(com, comText, Buffer.from([0xFF, 0xD9])); // EOI
  return Buffer.concat(parts);
}

/**
 * Minimal MP4: `ftyp` + `moov/mvhd` with a real creation_time (QuickTime epoch, UTC).
 * @param {string|null} isoUtc  e.g. "2016-12-10T10:09:50Z", or null for creation_time = 0 (unset)
 */
export function makeMp4(isoUtc, uniq) {
  const ftyp = Buffer.alloc(16);
  ftyp.writeUInt32BE(16, 0); ftyp.write('ftyp', 4, 'ascii');
  ftyp.write('isom', 8, 'ascii'); ftyp.writeUInt32BE(0, 12);
  const mvhd = Buffer.alloc(108);
  mvhd.writeUInt32BE(108, 0); mvhd.write('mvhd', 4, 'ascii'); // version 0, flags 0
  const secs = isoUtc ? Math.floor(Date.parse(isoUtc) / 1000) + QT_EPOCH_OFFSET : 0;
  mvhd.writeUInt32BE(secs, 12);        // creation_time
  mvhd.writeUInt32BE(secs, 16);        // modification_time
  mvhd.writeUInt32BE(1000, 20);        // timescale
  mvhd.writeUInt32BE(0, 24);           // duration
  mvhd.writeUInt32BE(0x00010000, 28);  // rate 1.0
  mvhd.writeUInt16BE(0x0100, 32);      // volume 1.0
  const moov = Buffer.alloc(8);
  moov.writeUInt32BE(8 + 108, 0); moov.write('moov', 4, 'ascii');
  // `free` box carries per-file uniqueness (real MP4s allow it anywhere top-level)
  const uniqBytes = Buffer.from('kpot-fixture:' + uniq, 'ascii');
  const free = Buffer.alloc(8);
  free.writeUInt32BE(8 + uniqBytes.length, 0); free.write('free', 4, 'ascii');
  return Buffer.concat([ftyp, moov, mvhd, free, uniqBytes]);
}

/** Minimal PNG: real signature + IHDR/IEND shells (CRCs zeroed — magic-detection fixtures only). */
export function makePng(uniq) {
  const sig = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  const ihdr = Buffer.alloc(25); // len(4) 'IHDR' 13-byte body + zero CRC
  ihdr.writeUInt32BE(13, 0); ihdr.write('IHDR', 4, 'ascii');
  ihdr.writeUInt32BE(1, 8); ihdr.writeUInt32BE(1, 12); ihdr[16] = 8; ihdr[17] = 0;
  const text = Buffer.from('kpot-fixture:' + uniq, 'ascii');
  const iend = Buffer.alloc(12); iend.write('IEND', 4, 'ascii');
  return Buffer.concat([sig, ihdr, text, iend]);
}

/** Minimal OGG: real 'OggS' magic + uniqueness padding. */
export function makeOgg(uniq) {
  return Buffer.concat([Buffer.from('OggS\0\0\0\0', 'ascii'), Buffer.from('kpot-fixture:' + uniq)]);
}

const text = (s) => Buffer.from(s, 'utf8');

// ---------------------------------------------------------------------------
// The case catalog — one entry per planted file.
// expected.date is the GROUND-TRUTH capture date ("YYYY-MM-DD HH:MM:SS" local, or null = undatable);
// expected.evidence names the strongest evidence KPOT is supposed to find it by.
// ---------------------------------------------------------------------------

/** @returns the full planted-case list (path separators are '/', converted on write) */
export function catalog() {
  return [
    // — date in the filename (Android camera convention) —
    { path: 'Мобилка/IMG_20140121_183801.jpg', body: makeJpeg(null, 'and1'),
      expected: { kind: 'photo', date: '2014-01-21 18:38:01', evidence: 'filename' } },
    // — "+"-twin pair: one char apart, different bytes, must NOT be merged as duplicates —
    { path: 'Мобилка/IMG_20140121_184626.jpg', body: makeJpeg(null, 'twinA'),
      expected: { kind: 'photo', date: '2014-01-21 18:46:26', evidence: 'filename', twin: 'plus-pair' } },
    { path: 'Мобилка/IMG_20140121_184626+.jpg', body: makeJpeg(null, 'twinB'),
      expected: { kind: 'photo', date: '2014-01-21 18:46:26', evidence: 'filename', twin: 'plus-pair' } },
    // — camera serial name, EXIF is the only evidence —
    { path: '100MEDIA/IMAG0180.jpg', body: makeJpeg('2011:03:05 14:20:33', 'htc1'),
      expected: { kind: 'photo', date: '2011-03-05 14:20:33', evidence: 'exif' } },
    // — EXIF and dir-name evidence agree (hand-sorted season subtree exists in real archive) —
    { path: '2013/Лето 2013/DSC01529.JPG', body: makeJpeg('2013:07:04 10:11:12', 'sony1'),
      expected: { kind: 'photo', date: '2013-07-04 10:11:12', evidence: 'exif' } },
    // — hand-sorted subtree, NO exif: dirname is the only evidence (year + season, autumn!) —
    { path: '2013/осень 2013/день рождения.jpg', body: makeJpeg(null, 'bday1'),
      expected: { kind: 'photo', date: null, year: 2013, season: 'осень', evidence: 'dirname' } },
    // — epoch-milliseconds filename (7 895 such files in the real archive) —
    { path: 'Разное/1374250121884.jpg', body: makeJpeg(null, 'epoch1'),
      expected: { kind: 'photo', date: '2013-07-19 18:08:41', evidence: 'filename-epoch' } },
    // — social-network export: 11-char id, no EXIF, no date anywhere → global "прочее" —
    { path: 'Из ВК/6V2qnCITQIE.jpg', body: makeJpeg(null, 'vk1'),
      expected: { kind: 'photo', date: null, evidence: 'none' } },
    // — Android screenshot with full timestamp + app suffix —
    { path: 'скриншоты/Screenshot_2017-05-27-19-34-56-006_com.android.chrome.png', body: makePng('scr1'),
      expected: { kind: 'photo', date: '2017-05-27 19:34:56', evidence: 'filename' } },
    // — WhatsApp date-only name —
    { path: 'Разное/IMG-20160404-WA0001.jpg', body: makeJpeg(null, 'wa1'),
      expected: { kind: 'photo', date: '2016-04-04 00:00:00', dateOnly: true, evidence: 'filename' } },
    // — Cyrillic *extension* (real case: `.без названия`) — media identified by content, not ext —
    { path: 'семейный архив/скан.без названия', body: makeJpeg('2008:12:31 09:00:00', 'cyr1'),
      expected: { kind: 'photo', date: '2008-12-31 09:00:00', evidence: 'exif', mediaByContentOnly: true } },
    // — broken camera clock: EXIF says 1979 → implausible, must be disputed, not trusted —
    { path: 'старое/IMAG0001.jpg', body: makeJpeg('1979:01:01 00:00:03', 'clock1'),
      expected: { kind: 'photo', date: null, evidence: 'exif-implausible', disputed: true } },
    // — exact duplicates: one shot, three byte-identical copies under different names/dirs —
    { path: '2014/DSC02000.JPG', body: makeJpeg('2014:08:10 12:00:00', 'dup1'),
      expected: { kind: 'photo', date: '2014-08-10 12:00:00', evidence: 'exif', dupGroup: 1 } },
    { path: 'копии/DSC02000.JPG', body: makeJpeg('2014:08:10 12:00:00', 'dup1'),
      expected: { kind: 'photo', date: '2014-08-10 12:00:00', evidence: 'exif', dupGroup: 1 } },
    { path: 'копии/лучшая фотка (копия).jpg', body: makeJpeg('2014:08:10 12:00:00', 'dup1'),
      expected: { kind: 'photo', date: '2014-08-10 12:00:00', evidence: 'exif', dupGroup: 1 } },
    // — video: mvhd creation_time and filename agree —
    { path: 'видео/VID_20161210_100950.mp4', body: makeMp4('2016-12-10T10:09:50Z', 'vid1'),
      expected: { kind: 'video', date: '2016-12-10 10:09:50', evidence: 'filename' } },
    // — video: mvhd only (name carries nothing) —
    { path: 'видео/MOV0001.mp4', body: makeMp4('2018-06-02T15:30:00Z', 'vid2'),
      expected: { kind: 'video', date: '2018-06-02 15:30:00', evidence: 'mvhd-utc' } },
    // — audio (voice note, WhatsApp-style dated name) → <year>/<season>/аудио/ per interview #001 —
    { path: 'голосовые/AUD-20150910-WA0003.ogg', body: makeOgg('aud1'),
      expected: { kind: 'audio', date: '2015-09-10 00:00:00', dateOnly: true, evidence: 'filename' } },
    // — junk → quarantine with provenance (interview #001 Q4 = C) —
    { path: '100MEDIA/Thumbs.db', body: text('fake thumbs db'),
      expected: { kind: 'junk', date: null, evidence: 'none' } },
    { path: 'Мобилка/.nomedia', body: text(''),
      expected: { kind: 'junk', date: null, evidence: 'none' } },
    // — non-media, non-junk → stays in place + report (interview #001 Q5 = A) —
    { path: 'доки/письмо.docx', body: text('fake docx bytes'),
      expected: { kind: 'other', date: null, evidence: 'none' } },
    { path: 'доки/заметка.txt', body: text('просто заметка'),
      expected: { kind: 'other', date: null, evidence: 'none' } },
  ];
}

// Files whose filesystem mtime is planted to the same fake "bulk copy day" — a real-archive artifact
// (18 656 files "modified" on one day). Their mtime must be detected as a spike and discounted.
const COPY_SPIKE_PATHS = new Set([
  'Из ВК/6V2qnCITQIE.jpg', 'Разное/1374250121884.jpg', 'Мобилка/IMG_20140121_183801.jpg',
]);

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Create the fixture tree under `root` (created if missing) and write `expected.json` into it.
 * @returns {Promise<object>} the manifest object
 */
export async function makeFixtureTree(root) {
  const cases = catalog();
  for (const c of cases) {
    const abs = join(root, ...c.path.split('/'));
    await mkdir(dirname(abs), { recursive: true });
    await writeFile(abs, c.body);
    // Plant a deterministic mtime: spike files get the fake copy day; the rest get a fixed old date,
    // so nothing depends on the machine clock at generation time.
    const mtime = COPY_SPIKE_PATHS.has(c.path) ? COPY_SPIKE_MTIME : new Date('2015-01-01T00:00:00Z');
    await utimes(abs, mtime, mtime);
  }
  const manifest = {
    fixtureVersion: FIXTURE_VERSION,
    copySpikeMtime: COPY_SPIKE_MTIME.toISOString(),
    files: cases.map(c => ({ path: c.path, size: c.body.length, expected: c.expected,
                             mtimeSpiked: COPY_SPIKE_PATHS.has(c.path) })),
  };
  await writeFile(join(root, 'expected.json'), JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  return manifest;
}

// CLI entry: node tests/fixtures/make.mjs <targetDir>
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const target = process.argv[2];
  if (!target) { console.error('usage: node tests/fixtures/make.mjs <targetDir>'); process.exit(2); }
  const m = await makeFixtureTree(target);
  console.log(`fixture tree v${m.fixtureVersion}: ${m.files.length} files planted in ${target}`);
}
