// src/plan/bucket.mjs — where does ONE file belong? Verdict + kind + original path → target segments.
// [TESTED: 2026-07-26 · tests/plan_phase3.test.mjs — technical-vs-custom dirs, date-structure dirs,
// the ambiguous «зима» case, and all 23 planted destinations against the fixture ground truth]
//
// This is the owner's desired layout (GOAL.md §«Желаемый формат на выходе») made executable. Every
// rule here is an owner decision from `MASTER_PLAN.md` §Decision log — none of it is this module's
// invention, and none of it may be "improved" without an interview:
//
//   <год>/<сезон>/[видео|аудио/][<кастомные папки>/]<исходное имя файла>
//
//   · five seasons, boundaries per interview #001 Q2      → src/plan/season.mjs
//   · photos at the season root, video → `видео/`, audio → `аудио/`   (owner in chat 2026-07-24)
//   · year known but season not         → `<год>/прочее`   (GOAL.md)
//   · nothing known                     → `ПРОЧЕЕ`         (GOAL.md: «глобальное ПРОЧЕЕ»)
//   · dir-cohort ASSUMED year           → `<год>/прочее`, always flagged (decision log 2026-07-24)
//   · junk                              → `ПРОЧЕЕ/_мусор`, provenance kept (interview #001 Q4)
//   · duplicates                        → `ПРОЧЕЕ/_дубликаты`, provenance kept (owner 2026-07-26)
//   · `other` files                     → stay where they are (interview #001 Q5)
//   · custom parent dirs preserved as nesting; TECHNICAL ones dropped (owner 2026-07-26)
//
// Determinism: this module is pure — same asset in, same segments out, on every machine. It reads
// no clock and no filesystem (AGENT_GUIDE → canonical order).

import { SEASONS, seasonForMonth } from './season.mjs';

/** Top-level bucket for everything undatable, plus its two quarantine areas. */
export const GLOBAL_OTHER = 'ПРОЧЕЕ';
export const JUNK_DIR = '_мусор';
export const DUPES_DIR = '_дубликаты';
/** Per-year bucket for "this year for sure, but which season is unknown" (GOAL.md). */
export const YEAR_OTHER = 'прочее';

/** Media-kind subdirectory inside a season (photos stay at the season root). */
const KIND_SUBDIR = { video: 'видео', audio: 'аудио', photo: null };

/** The owner's season words (dirname evidence) → canonical season directory names. */
const SEASON_WORD_TO_DIR = {
  весна: SEASONS.SPRING,
  лето: SEASONS.SUMMER,
  осень: SEASONS.AUTUMN,
  // 'зима' is deliberately absent: a bare "Зима 2020" cannot say WHICH winter bucket it means
  // (the year has two — Jan–Feb and Dec). Guessing would silently misplace a file, so such a file
  // goes to `<год>/прочее` and the plan reports it as a disputed case.
};

/**
 * Directory names that are TECHNICAL — generated by a device, an app or the OS rather than named by
 * the owner. They are dropped instead of being recreated inside the library.
 *
 * Sourced, not invented: `researches/02_real_archive_survey.md` §Directory structure observed
 * `100MEDIA`-style device-dump dirs in the owner's real archive; `DCIM/<3 digits + tag>` is the
 * universal camera-filesystem convention (DCF). The Russian generic content words are here for a
 * concrete reason: without them a folder literally named `видео` would nest inside our own `видео/`
 * subdir and produce `…/видео/видео/`.
 */
const TECHNICAL_DIR_NAMES = new Set([
  'dcim', 'camera', 'camera roll', 'screenshots', 'screenshot', 'downloads', 'download',
  'pictures', 'my pictures', 'images', 'photos', 'video', 'videos', 'my videos', 'movies',
  'audio', 'music', 'sounds', 'bluetooth', 'sent', 'received',
  'whatsapp images', 'whatsapp video', 'whatsapp audio', 'whatsapp documents',
  'telegram', 'telegram images', 'telegram video', 'viber images', 'viber',
  // Russian generic content-type words — these collide with our own layout subdirs
  'видео', 'аудио', 'фото', 'музыка', 'картинки', 'изображения', 'загрузки',
]);

/** `100MEDIA`, `101APPLE`, `100ANDRO`, `100CANON` … — the DCF device-dump directory pattern. */
const DEVICE_DUMP_RE = /^\d{3}[A-Za-z][A-Za-z0-9_-]{0,9}$/;

/** Year and season tokens, used to recognize a purely structural date directory. */
const YEAR_TOKEN_RE = /(?:^|[^\d])(?:19|20)\d{2}(?=[^\d]|$)/g;
const SEASON_TOKEN_RE = /(зима|весна|лето|осень)/gi;

/**
 * A directory whose name carries ONLY date structure — `2013`, `Лето 2013`, `осень_2013`,
 * `Зима 2020`. These are the owner's own hand-made year/season shelves: KPOT rebuilds that
 * structure itself, so re-nesting them would produce `2013/Лето/2013/Лето 2013/`.
 * A name with anything left after removing the date tokens (`отпуск 2005`) is the owner's, and stays.
 */
export function isDateStructureDir(segment) {
  const rest = segment
    .replace(YEAR_TOKEN_RE, ' ')
    .replace(SEASON_TOKEN_RE, ' ')
    .replace(/[\s_\-.,()]+/g, '');
  return rest === '' && /\d|зима|весна|лето|осень/i.test(segment);
}

/**
 * Is this one path segment a technical directory (dropped) rather than the owner's own name (kept)?
 * The owner's decision of 2026-07-26 was "preserve everything EXCEPT technical dirs".
 */
export function isTechnicalDir(segment) {
  const s = segment.trim().toLowerCase();
  if (s === '') return true;
  if (TECHNICAL_DIR_NAMES.has(s)) return true;
  if (DEVICE_DUMP_RE.test(segment.trim())) return true;
  return isDateStructureDir(segment.trim());
}

/**
 * The owner-named ancestor directories of a file, outermost→innermost, technical ones removed.
 * @param {string} relPath  '/'-separated path relative to the scan root
 * @returns {string[]}
 */
export function customDirs(relPath) {
  return relPath.split('/').slice(0, -1).filter((seg) => !isTechnicalDir(seg));
}

/** Year/month of a 'dated' verdict. Wall-clock when we have it; otherwise the instant read as UTC. */
function yearMonthOf(verdict) {
  if (verdict.date) {
    // 'YYYY-MM-DD HH:MM:SS' — local wall clock exactly as the camera/filename wrote it
    return { year: Number(verdict.date.slice(0, 4)), month: Number(verdict.date.slice(5, 7)) };
  }
  // A UTC instant (mvhd) whose original timezone is unknown. Reading it as UTC is DETERMINISTIC —
  // using the machine's local zone would make the same archive sort differently on two computers.
  // The cost is a possible one-bucket error for a shot taken within hours of a season boundary;
  // planBucket flags exactly those as disputed rather than hiding the risk.
  const d = new Date(verdict.instant);
  return { year: d.getUTCFullYear(), month: d.getUTCMonth() + 1 };
}

/** Hours from an instant to the nearest season boundary — the mis-shelving risk window. */
const BOUNDARY_MARGIN_HOURS = 12;
function nearSeasonBoundary(verdict) {
  if (!verdict.instant) return false; // wall-clock sources carry no timezone risk
  const d = new Date(verdict.instant);
  const month = d.getUTCMonth() + 1;
  const day = d.getUTCDate();
  const hour = d.getUTCHours();
  const seasonStarts = new Set([1, 3, 6, 9, 12]); // Jan, Mar, Jun, Sep, Dec — see season.mjs
  const daysInMonth = new Date(Date.UTC(d.getUTCFullYear(), month, 0)).getUTCDate();
  const atStart = day === 1 && seasonStarts.has(month) && hour < BOUNDARY_MARGIN_HOURS;
  const atEnd = day === daysInMonth && seasonStarts.has(month === 12 ? 1 : month + 1)
    && hour >= 24 - BOUNDARY_MARGIN_HOURS;
  return atStart || atEnd;
}

/**
 * Decide the destination of one asset.
 *
 * @param {object} asset  annotated asset ({path, kind, verdict, …})
 * @param {{isDuplicateCopy?: boolean}} [opts]  the asset is a non-keeper copy of a duplicate group
 * @returns {{action: 'move'|'stay', segments: string[], name: string, reason: string,
 *            disputed: Array<{issue: string, detail?: string}>}}
 *          `segments` are the target directories under the root; `name` is the file's own name,
 *          always preserved (GOAL.md: «кастомные названия желательно сохранить»).
 */
export function planBucket(asset, { isDuplicateCopy = false } = {}) {
  const name = asset.path.split('/').at(-1);
  const disputed = [];
  // Provenance-preserving flat name for the two quarantine areas: the original directory travels
  // WITH the file, so a quarantined item is always traceable back to where it came from.
  const flatName = asset.path.split('/').join('__');

  if (isDuplicateCopy) {
    return { action: 'move', segments: [GLOBAL_OTHER, DUPES_DIR], name: flatName,
      reason: 'an exact copy of a file kept elsewhere in the library', disputed };
  }
  if (asset.kind === 'junk') {
    return { action: 'move', segments: [GLOBAL_OTHER, JUNK_DIR], name: flatName,
      reason: 'system junk — quarantined, never deleted', disputed };
  }
  if (asset.kind === 'other') {
    return { action: 'stay', segments: [], name,
      reason: 'not a media file — left exactly where the owner put it', disputed };
  }

  const verdict = asset.verdict ?? { status: 'unknown' };
  const sub = KIND_SUBDIR[asset.kind] ?? null;
  const tail = [...(sub ? [sub] : []), ...customDirs(asset.path)];

  if (verdict.status === 'unknown') {
    return { action: 'move', segments: [GLOBAL_OTHER, ...tail], name,
      reason: 'no usable date evidence — the global «прочее» bucket', disputed };
  }

  // An assumed (dir-cohort) year is a flagged GUESS: the year bucket is right enough to be useful,
  // the season is not claimed at all, and the owner always sees it (decision log 2026-07-24).
  if (verdict.assumed) {
    disputed.push({ issue: 'assumed-year',
      detail: `year ${verdict.year} inferred from confidently-dated neighbours in the same directory` });
    return { action: 'move', segments: [String(verdict.year), YEAR_OTHER, ...tail], name,
      reason: `assumed year ${verdict.year} (from its directory's dated neighbours) — season not claimed`, disputed };
  }

  if (verdict.status === 'partial') {
    const seasonDir = verdict.season ? SEASON_WORD_TO_DIR[verdict.season] : null;
    if (verdict.season && !seasonDir) {
      disputed.push({ issue: 'ambiguous-season',
        detail: `the directory says «${verdict.season}», but a year has two winter buckets — cannot tell which` });
    }
    if (seasonDir) {
      return { action: 'move', segments: [String(verdict.year), seasonDir, ...tail], name,
        reason: `year and season taken from the owner's own directory name`, disputed };
    }
    return { action: 'move', segments: [String(verdict.year), YEAR_OTHER, ...tail], name,
      reason: `year ${verdict.year} is certain, the season is not`, disputed };
  }

  // status === 'dated'
  const { year, month } = yearMonthOf(verdict);
  if (nearSeasonBoundary(verdict)) {
    disputed.push({ issue: 'timezone-boundary',
      detail: 'the only date evidence is a UTC instant within hours of a season boundary — the '
        + 'original timezone is unknown, so the neighbouring season is possible' });
  }
  return { action: 'move', segments: [String(year), seasonForMonth(month), ...tail], name,
    reason: `dated ${verdict.date ?? new Date(verdict.instant).toISOString()} (${verdict.winner})`, disputed };
}
